# Generated by Django 2.1 on 2019-02-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'email')},
        ),
    ]
