# Generated by Django 2.1.7 on 2019-02-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('work', models.PositiveSmallIntegerField(choices=[(0, 'Author'), (1, 'Artist'), (2, 'Assistant')])),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField()),
                ('number', models.SmallIntegerField()),
                ('prefix_title', models.CharField(blank=True, max_length=20, null=True)),
                ('order_number', models.SmallIntegerField()),
                ('volume', models.SmallIntegerField()),
                ('active', models.IntegerField()),
                ('state', models.IntegerField()),
                ('date', models.IntegerField()),
            ],
            options={
                'db_table': 'chapters',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_type', models.PositiveIntegerField(blank=True, choices=[(0, 'gatunek'), (1, 'grupa demograficzna'), (2, 'czasy'), (3, 'miejsce'), (4, 'inne')], null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50)),
                ('hide', models.IntegerField()),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_kanji', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('birthplace', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[(0, '0'), (1, 'A'), (2, 'B'), (3, 'AB')], max_length=2, null=True)),
                ('description', models.TextField()),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_pl', models.CharField(db_column='long_name_PL', max_length=255)),
                ('name_en', models.CharField(db_column='long_name_EN', max_length=255)),
                ('chapter_prefix', models.CharField(max_length=25)),
                ('state', models.IntegerField(choices=[(0, 'ukryty'), (1, 'aktywny'), (2, 'zakończony'), (3, 'porzuczony'), (4, 'zlicencjonowany')])),
                ('type', models.IntegerField()),
                ('is_hentai', models.IntegerField()),
                ('description', models.TextField()),
                ('total_volumes', models.SmallIntegerField()),
                ('state_japan', models.IntegerField()),
                ('text_state', models.TextField(blank=True, null=True)),
                ('authors', models.ManyToManyField(through='projects.Author', to='projects.Person')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectGenre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Genre')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'db_table': 'project_genre',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('number', models.IntegerField()),
                ('specific_name', models.CharField(blank=True, max_length=30, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'db_table': 'volumes',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Chapter')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'works',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='genres',
            field=models.ManyToManyField(through='projects.ProjectGenre', to='projects.Genre'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='author',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Person'),
        ),
        migrations.AddField(
            model_name='author',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('user', 'chapter', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='projectgenre',
            unique_together={('genre', 'project')},
        ),
    ]
