# Generated by Django 2.1 on 2019-02-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='long_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='long_name_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='long_name_pl',
            new_name='name_pl',
        ),
    ]
