# Generated by Django 2.1.7 on 2019-03-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='project',
            new_name='title',
        ),
    ]
