# Generated by Django 2.1.7 on 2019-03-09 02:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('no_hentai', django.db.models.manager.Manager()),
            ],
        ),
    ]
