# Generated by Django 2.1.7 on 2019-03-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190306_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='state_japan',
            field=models.IntegerField(choices=[(0, 'aktywne'), (1, 'zakończone')]),
        ),
    ]
