# Generated by Django 2.1.7 on 2019-03-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190309_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsinneed',
            name='role',
        ),
        migrations.AddField(
            model_name='projectsinneed',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Job'),
            preserve_default=False,
        ),
    ]
