# Generated by Django 2.1.7 on 2019-03-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190306_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_name',
            new_name='name',
        ),
    ]
