# Generated by Django 2.1.7 on 2019-03-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190309_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='date',
            field=models.DateField(),
        ),
    ]
