# Generated by Django 2.1.7 on 2019-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190309_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsinneed',
            name='jobText',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
