# Generated by Django 2.1.7 on 2019-03-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectsinneed_jobtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsinneed',
            old_name='jobText',
            new_name='job_text',
        ),
    ]
