# Generated by Django 2.1.7 on 2019-04-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190326_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='next_job',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.IntegerField(choices=[(0, 'Ukryty'), (1, 'Aktywny'), (2, 'Zakończony'), (3, 'Porzuczony'), (4, 'Zlicencjonowany'), (5, 'Wstrzymany')]),
        ),
        migrations.AlterField(
            model_name='title',
            name='state_japan',
            field=models.IntegerField(choices=[(0, 'Powstaje'), (1, 'Zakończona'), (2, 'Wsztrymana')]),
        ),
    ]
