# Generated by Django 2.1.7 on 2019-04-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190401_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='next_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Job'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
