# Generated by Django 2.1 on 2019-02-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190221_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
