# Generated by Django 2.1 on 2019-02-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='user_id',
            new_name='user',
        ),
    ]
